version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ProjectPersonalType
    container_name: db_personal
    volumes:
      - ./postgres:/var/lib/postgresql/data      
